### PR TITLE
add support for nested folders and files

### PR DESCRIPTION
**Pull request by srivastavankit**

### CODE REVIEW

**Comment by blampe** [comment]
Thanks for the PR @srivastavankit! @kriskowal will take a look.

Are there any backwards-compatibility issues to consider? For example if a client on an older version pulls down a path with nested directories, will everything just work?

**Comment by srivastavankit** [comment]
@blampe Yes, there shouldn't be any backward compatibility issues.

**Comment by kriskowal** [comment]
Here’s my attempt to reverse engineer a description for this change:

> Currently, IDL does not detect a change to an IDL if it includes on files in subdirectories. This change enables IDL to detect such changes by digesting the hash of every file in the IDL's transitive directory tree.

**Comment by kriskowal** [comment]
@malandrew recommends holding off on landing this. We’ll discuss Monday.

**Comment by malandrew** [comment]
Why was this landed while we're still discussing this change?

**Pull request merged**
