### PR TITLE
Folders are something that exist on Windows 95, not Unix systems

### PR DESCRIPTION
**Pull request by eklitzke**
Thanks dudes.

### CODE REVIEW

**Comment by zheller** [comment]
https://www.youtube.com/watch?v=dFUlAQZB9Ng

**Comment by breerly** [comment]
sure why not 

cc eskil :P

**Comment by eklitzke** [comment]
This does break compatibility with one of the existing config options, btw. Sorry.

**Comment by malandrew** [comment]
+1. Feel free to land after you fix the idlrc files in puppet and uber-developer.

**Comment by prashantv** [comment]
image

#wontfix

**Comment by breerly** [comment]
screen shot 2016-02-22 at 6 05 45 pm

**Comment by breerly** [comment]
Except... from the cli (which is the ultimate source of truth):

screen shot 2016-02-22 at 6 07 56 pm

**Comment by malandrew** [comment]
@eklitzke Add a patch that reads from `repositoryDirectory` if available and falls back to `repositoryFolder` if not found.

**Comment by eklitzke** [comment]
@prashantv cool dude thanks for the Unix history lesson

**Comment by eklitzke** [comment]
POISX: http://pubs.opengroup.org/onlinepubs/7908799/xsh/dirent.h.html (see also: opendir, closedir, readdir, rewiddir, weekdir, telldir, and so forth)

@malandrew will do, I'll see if I can keep backwards compatibility too.

**Comment by splaice** [comment]
screen shot 2016-02-22 at 6 37 10 pm

ls on OS X says it is a directory too

**Comment by mranney** [comment]
Sadly, things like npm have this problem as well. Kids these days.

At the end of the day, both terms are, I sadly must admit, interchangeable. All of the low level APIs call them "directories", but high level APIs call them "folders". We still do "mkdir" and "cd" in every shell. I think "directories" is the way to go for something like IDL, but ultimately it probably doesn't matter.

**Comment by eklitzke** [comment]
I'm curious: what are some reputable high level APIs that call them "folders"?

Even on Apple's own website, which admittedly does use the word "folder" in Finder, they are nearly always called directories at https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html and https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html (a tiny handful exceptions aside, which I presume are mistakes from their copywriting team).

I'm not saying there are no examples Apple/Linux/BSD software that uses the word "folder", but I'd be interested in finding some well regarded high level APIs that call them folders as you say.

**Comment by breerly** [comment]
@eklitzke 

I imagine that everyone agrees with you and simultaneously doesn't feel strongly enough/doesn't care enough to make the change.

If you have a backwards compat story/this doesnt break anything - I don't see any reason why we couldn't merge it.

**Comment by eklitzke** [comment]
I updated the diff with a new commit that falls back to use `repositoryFolder` if `repositoryDirectory` is not present. I have no idea what our JS style is but I stuck to 79 character lines and used C++ `//` style comments rather than C `/* */` comments.

Let me know if I need to change anything or if the style is incorrect.

**Comment by malandrew** [comment]
@eklitzke LGTM

**Comment by breerly** [comment]
:balloon: :balloon: :balloon:

**Pull request merged**
