### PR TITLE
Fix npm apocalypse 

### PR DESCRIPTION
**Pull request by mihai-chiorean**
read-json semver is looking for non-existing version.

### CODE REVIEW

**Comment by zmt** [comment]
LGTM

**Comment by twexler** [comment]
Uh, what?

**Comment by twexler** [comment]
https://www.npmjs.com/package/read-json Has 1.0.3...

**Comment by zmt** [comment]
Apparently unpm masks the external read-json:
```
✔  [ztrain@gallifrey] ~/stuff/uber-puppet-manifests [master ↓·74|⚑ 1] 
11:42 $ npm info read-json versions
npm http request GET https://unpm.uberinternal.com/read-json
npm http 200 https://unpm.uberinternal.com/read-json
[ '0.1.0', '0.2.0', '1.0.0' ]
```

**Comment by twexler** [comment]
So that means we need to get unpm to have the latest, not that we downgrade our version...

**Comment by mihai-chiorean** [comment]
it works fine with both. ^1.0.0 will install the latest 1.x.x. Perviously it was fixed on 1.0.3 and nothing else. When we upgrade unpm, it will get the latest 1.x.x

**Pull request merged**
