### PR TITLE
Better IDL list interface

### PR DESCRIPTION
**Pull request by malandrew**
Solves #14, #16, #17 and #18

@breerly @kriskowal @Raynos

### CODE REVIEW

**Comment by breerly** [comment]
@malandrew yo dude! try and submit changes in separate, whole, and cohesive PR's in the future!

**Comment by breerly** [comment]
Can you attach a screenshot of the new `idl list` command?

**Comment by malandrew** [comment]
screen shot 2015-10-21 at 2 50 13 pm

**Comment by breerly** [comment]
Looking good. Let's:

* remove the underline on the column headers, the uppercase and blue is enough.
* you don't need hyphens for empty values in the LOCAL column, causes the ui to be busy.

**Pull request merged**
