### PR TITLE
Feature: Fetch thrift dependencies

### LINKED ISSUE #44: fetch dependent/included files
This is a thrift-specific feature request. If I fetch `some.repo/foo.thrift` which includes `bar.thrift` we should automatically issue another fetch for `some.repo/bar.thrift`. We would need to keep track of which files have already been fetched to prevent loops.

### PR DESCRIPTION
**Pull request by malandrew**
This closes #44 

cc/ @raynos @kriskowal

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by malandrew** [comment]
@Raynos @blampe  before I land this, is it worth possibly putting this behind a --recursive flag or should fetching dependencies be the default behavior?

**Comment by blampe** [comment]
Default behavior would be reasonable IMO (it matches how I expect other package managers to work). @breerly would you agree?

Have we verified this against some production files?

**Comment by breerly** [comment]
Recursive should probably be default - I would be surprised if this only worked 1 level, for example.

Later we can invest in a `--no-recurse` flag if there is demand.

**Comment by malandrew** [comment]
@blampe The test I wrote for this feature actually uses a version of the stooges idl file. Is it possible there is an edge-case I didn't account for? Possibly, but off the top of my head I can't think of what that edge-case might be. I can look into idl-registry and try some and see what happens.

**Comment by malandrew** [comment]
@breerly It follows multiple levels because it checks for includes on each new fetch, but it only every fetches an include exactly once.

**Comment by malandrew** [comment]
@blampe I tried with 5 different services in idl-registry and it worked great. I didn't encounter an entirely unrelated bug that surfaced in the way I was testing. The issue is detailed in #52 . This bug exists independent of this feature, so I think this feature is good to land.

**Comment by malandrew** [comment]
Wait.... The mc team is doing something really odd in some repos where their relative includes are actually reaching all the way outside the repo (via `../../../../`), which breaks this feature. That's really unorthodox use of idl. 

@blampe @breerly Your thoughts?

**Comment by blampe** [comment]
They must be checking in something outside of IDL. Make a best-effort I guess -- if you explicitly fetch something that's unavailable that's an error, but if you do it as part of the recursive step we should ignore it and move on.

**Comment by breerly** [comment]
I wonder if it's better to only support fetching based on files *inside* the `idl/` dir

**Comment by malandrew** [comment]
@blampe @breerly I found a workaround. I am ignoring anything outside the idl directory.

**Comment by breerly** [comment]
I like that +1

**Pull request merged**
